from .queries import (
    VirusTotalQuery,
    ThreatFoxQuery,
    AlienVaultQuery,
    IBMXForceQuery,
    ShodanQuery,
    APIVoidQuery,
    AbuseIPDBQuery,
    MalwareBazaarQuery,
    URLHausQuery,
    GreyNoiseQuery,
    URLScanQuery,
    OnionooQuery,
    PhishTankQuery,
    OpenPhishQuery,
    CINSscoreQuery,
    IPWhoisQuery,
)


# Dispatch table mapping module types to their respective query classes, supported indicator types, and weights
MODULE_QUERIES = {
    'VirusTotal': {
        'class': VirusTotalQuery,
        'supported_types': ['file', 'url', 'ip', 'domain'],
        'default_weight': 1.5,
        'description': 'VirusTotal offers a robust analysis tool for files, URLs, and IP addresses to check for malicious content.',
        'website': 'https://www.virustotal.com/',
        'type': 'api',
    },
    'ThreatFox': {
        'class': ThreatFoxQuery,
        'supported_types': ['file', 'url', 'ip', 'domain'],
        'default_weight': 1.0,
        'description': 'ThreatFox provides threat intelligence data for a variety of indicator types.',
        'website': 'https://www.threatfoxapi.com/',
        'type': 'api',
    },
    'AlienVault': {
        'class': AlienVaultQuery,
        'supported_types': ['file', 'url', 'ip', 'domain'],
        'default_weight': 1.2,
        'description': 'AlienVault provides real-time threat intelligence, including detailed information about malicious activity.',
        'website': 'https://www.alienvault.com/',
        'type': 'api',
    },
    'IBM X-Force': {
        'class': IBMXForceQuery,
        'supported_types': ['file', 'url', 'ip', 'domain'],
        'default_weight': 1.0,
        'description': 'IBM X-Force offers a threat intelligence platform, providing advanced security data.',
        'website': 'https://www.ibm.com/security/x-force',
        'type': 'api',
    },
    'Shodan': {
        'class': ShodanQuery,
        'supported_types': ['ip'],
        'default_weight': 0.8,
        'description': 'Shodan is a search engine for internet-connected devices, offering IP address data for security research.',
        'website': 'https://www.shodan.io/',
        'type': 'api',
    },
    'APIVoid': {
        'class': APIVoidQuery,
        'supported_types': ['file', 'url', 'ip', 'domain'],
        'default_weight': 0.9,
        'description': 'APIVoid provides a range of services for querying domain, IP, and URL reputation.',
        'website': 'https://www.apivoid.com/',
        'type': 'api',
    },
    'AbuseIPDB': {
        'class': AbuseIPDBQuery,
        'supported_types': ['ip'],
        'default_weight': 0.7,
        'description': 'AbuseIPDB provides access to a database of reported IP addresses associated with malicious activity.',
        'website': 'https://www.abuseipdb.com/',
        'type': 'api',
    },
    'GreyNoise': {
        'class': GreyNoiseQuery,
        'supported_types': ['ip'],
        'default_weight': 0.6,
        'description': 'GreyNoise provides noise reduction for threat intelligence by filtering out known benign IPs.',
        'website': 'https://www.greynoise.io/',
        'type': 'api',
    },
    'MalwareBazaar': {
        'class': MalwareBazaarQuery,
        'supported_types': ['hash'],
        'default_weight': 1.0,
        'description': 'MalwareBazaar provides intelligence and metadata about malware samples, including hashes and file information.',
        'website': 'https://bazaar.abuse.ch/',
        'type': 'api',
    },
    'URLHaus': {
        'class': URLHausQuery,
        'supported_types': ['url', 'domain'],
        'default_weight': 1.0,
        'description': 'URLHaus tracks and shares information about malicious URLs used for malware distribution.',
        'website': 'https://urlhaus.abuse.ch/',
        'type': 'api',
    },
    'URLScan': {
        'class': URLScanQuery,
        'supported_types': ['url'],
        'default_weight': 1.3,
        'description': 'URLScan provides detailed security and reputation analysis of URLs.',
        'website': 'https://urlscan.io/',
        'type': 'api',
    },
    'Onionoo': {
        'class': OnionooQuery,
        'supported_types': ['ip'],
        'default_weight': 0.9,
        'description': 'Tor Node Information.',
        'website': 'https://metrics.torproject.org/onionoo.html/',
        'type': 'builtin',
    },
    'PhishTank': {
        'class': PhishTankQuery,
        'supported_types': ['url'],
        'default_weight': 1.0,
        'description': 'PhishTank is a community-driven anti-phishing service that provides verified phishing URLs.',
        'website': 'https://www.phishtank.com/',
        'type': 'api',
    },
    'OpenPhish': {
        'class': OpenPhishQuery,
        'supported_types': ['url'],
        'default_weight': 1.0,
        'description': 'OpenPhish offers automated phishing intelligence feeds with active and verified phishing URLs.',
        'website': 'https://openphish.com/',
        'type': 'builtin',
    },
    'CINSscore': {
        'class': CINSscoreQuery,
        'supported_types': ['ip'],
        'default_weight': 0.7,
        'description': 'CINSscore provides a threat intelligence feed of known malicious IPs.',
        'website': 'https://cinsscore.com/',
        'type': 'builtin',
    },
    'IPWhois': {
        'class': IPWhoisQuery,
        'supported_types': ['ip'],
        'default_weight': 0.0,
        'description': 'Basic IP WHOIS.',
        'website': 'https://ipwho.is/',
        'type': 'builtin',
    },
}


