# Generated by Django 5.2 on 2025-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_module_remove_usermodule_module_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodule",
            name="api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usermodule",
            name="api_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
