# Generated by Django 5.2 on 2025-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_usermodule_api_key_usermodule_api_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="module",
            name="indicator_types",
            field=models.ManyToManyField(
                blank=True, related_name="modules", to="search.indicatortype"
            ),
        ),
    ]
