# Generated by Django 5.2 on 2025-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_indicatortype_module_indicator_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodule",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
