# Generated by Django 5.2 on 2025-04-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_module_default_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquery",
            name="risk_score",
            field=models.FloatField(default=0),
        ),
    ]
