# Generated by Django 5.2 on 2025-04-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0008_alter_searchquery_result_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
