# Generated by Django 5.2 on 2025-04-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0009_module_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="type",
            field=models.CharField(
                choices=[("api", "API Connected"), ("builtin", "Built-in")],
                default="api",
                max_length=10,
            ),
        ),
    ]
